
spring:
  profiles:
    active: dev
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

kakao:
  client_id: ef1dbd44e7ef6634e3fec53570d8fd11
  redirect_uri: http://localhost:5173/oauth/callback/kakao

jwt:
  secretKey: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

dart:
  apiKey: e361bdf14cb2ff30cbd64501d5b51b502734199d
  path: C:/Users/SSAFY/Desktop/