server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.35.54.104:3306/antoday?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
    username: root
    password: omfg


kakao:
  client_id: ef1dbd44e7ef6634e3fec53570d8fd11
  redirect_uri: https://antoday.com/oauth/callback/kakao